### ISSUE TITLE
Add a blacklist of modules to warn the user about?

### ISSUE THREAD

**Issue by cclauss** [dgelessus/fistutils#1]
Given:

```
1) pip MUST NOT BE USED TO UPDATE ITSELF!
[ ... ]
3) Only pure Python modules can be installed.
```

would it be useful this version of **pip to maintain a blacklist of modules to complain about**:

`pip install pip`  _--> this is not recommend, see http://rtfm.org/fistutils_
`pip install clibbasedmodule`  _--> clibbasedmodule is not pure Python, see http://rtfm.org/fistutils_

You could always allow: `pip install --force clibbasedmodule` for those who want to experiment.

**Comment by dgelessus** [comment]
It would probably be good to at least remove the pip update check, so there's no nag message when the next `pip` version is released.

As for non-Python modules, I don't think they need to be blacklisted explicitly. `distutils` raises an error when any of the compiler functions are called. That should automatically make the installation fail.

**Comment by dgelessus** [comment]
OK, I've added a `pip.conf` in 54f3e146b61e3b736341efb35c85734dcb4cb1a5 which disables the update check for pip.
